name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode: [development, production]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build application for ${{ matrix.mode }} mode
        run: yarn run build --mode ${{ matrix.mode }}
        env:
          VITE_MODE: ${{ matrix.mode }}

      - name: Upload production artifacts
        if: matrix.mode == 'production'
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: dist

      - name: Upload development artifacts
        if: matrix.mode == 'development'
        uses: actions/upload-artifact@v2
        with:
          name: development-build
          path: dist
